Add links in the footer
moja-global/contributors_website pull request #4
Opened 2020-09-25 09:14 UTC by shubhamkarande13

# Pull Request Template

## Description
Gsoc.png & Linux.png were removed and hence have been commented out.

I have added relevant links to the footer under @Tlazypanda 's guidance.
Fixes #1 partially

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] My changes generate no new warnings
- [ ] I have checked my code and corrected any misspellings
- [ ] I have tagged the reviewers in a comment below incase my pull request is ready for a review
- [ ] I have signed the commit message to agree to Developer Certificate of Origin (DCO) (to certify that you wrote or otherwise have the right to submit your contribution to the project.) by adding "--signoff" to my git commit command.

@Tlazypanda @gmajan @Patamap

2020-09-25 09:36 UTC, Tlazypanda requested changes
Hey @shubhamkarande13 have left some tiny changes that we can possibly incorporate :v:

2020-09-25 09:36 UTC, Tlazypanda commented on contributors_website/src/ossComponent.js
> +//import Linux from './images/linux.png';
Hey @shubhamkarande13 can you remove these lines completely? :sweat_smile:

2020-09-25 09:36 UTC, Tlazypanda commented on contributors_website/src/footerComponent.js
> +     'mailto:info@moja.global',
Hey @shubhamkarande13 the mail to has already been set in the mail icon so can we replace this with another link? Also the team link is not redirecting to team should we rename it to something else or change that link? :sweat_smile:

2020-09-25 10:05 UTC, shubhamkarande13 commented on contributors_website/src/footerComponent.js
> +     'mailto:info@moja.global',
What do you suggest for 'Contact Us' then?😅

For the team link, I thought that All Contributors section on about moja global page would look good. We don't have a team section on moja.global as well😅
Also, we have all contributors list too on the page so the Team section seems redundant.
Or we could expand the all contributors list to show all contributors by scrolling through the component.😅

2020-09-25 14:43 UTC, shubhamkarande13 commented on contributors_website/src/ossComponent.js
> +//import Linux from './images/linux.png';
Done. 😁

2021-01-16 02:06 UTC, aornugent commented
@shubhamkarande13 - what does this PR need before it can be merged?

2021-03-07 19:46 UTC, shubhamkarande13 commented
@aornugent I am closing this PR as all the features have been added by Sneha already.

2021-03-07 19:46 UTC, closed without merging